### ISSUE TITLE
Is this repo still alive ? 

### ISSUE THREAD

**Issue by lupuszr** [jonlaing/rationale#20]
Hi @jonlaing :) 

I don't see much activity on this repo, in the meantime I'm actively adding new features for  my personal needs  on a fork and I presume it would be a good thing to update the main repo as well.

**Comment by jonlaing** [comment]
Hey sorry about that. I've been nose deep in a job. I've seen the pull requests. I'll get those merged soon. Sorry again!

**Comment by beizhedenglong** [comment]
hi @jonlaing, I can help you maintain this repo.

**Comment by davesnx** [comment]
This seems a very abandoned project but with many many potentials to influence further APIs from Belt. Why not take a little bit more of care? :D

**Comment by jonlaing** [comment]
Hey everyone. Apologies for letting this project slip. I was under a lot of pressure at my job, and didn't have time to go through the pull requests and make sure they were solid. I've just gone through all of them and merged.

If y'all really like this project, I could probably use some help managing it. If you're interested in helping me, hit me up at jon [at] jonlaing.io

Thanks everyone for your contributions!

**Comment by jonlaing** [comment]
Oh, also, of course, I've published to NPM, so this should all be up to date. Again, sorry for the delay

**Comment by lupuszr** [comment]
I would gladly help you, I will contact you in the following days through mail
